### ISSUE TITLE
Link to docs in main GitHub page

### ISSUE THREAD

**Issue by JoshuaLampert** [mikeingold/MeshIntegrals.jl#113]
Only a small thing: I think you changed the link to the docs in the main page of the GitHub repo to point to the dev version because of the problems with uploading the docs for the tagged versions @mikeingold. Now that this is sorted out and the stable version is linked correctly, it would be nice if this could be switched back to point to the stable one.

**Comment by mikeingold** [comment]
You’re correct. Since the stable links were still pointing to an old version I changed the sidebar link to point to dev and swapped the badge order.

I just changed the sidebar link back. We can swap the badge order back in whatever PR comes next.

**Comment by JoshuaLampert** [comment]
Thanks!
