### ISSUE TITLE
Unable to integrate `Frustum` pending upstream changes

### ISSUE THREAD

**Issue by mikeingold** [mikeingold/MeshIntegrals.jl#57]
Integration over `Frustum` and `FrustumSurface` is not explicitly prevented, but these types are not officially supported.

Known issues, as of 30-Aug-2024:
- Meshes.jl has not yet defined a parametric function for `Frustum`
- Tests for integrating `FrustumSurface` in #51 initially yielded seemingly-incorrect values, then generated very lengthy test time increases (CI cancelled at ~30 minutes)

For now, I'm just marking these types as "not supported" pending any real demand signal for them.

**Comment by mikeingold** [comment]
Improvements implemented in #51 and #68 were able to fix the previous issues integrating `FrustumSurface` types, so those are now officially supported.

However, Meshes has not yet implemented a parametric function for `Frustum`, so those remain unsupported until one is implemented upstream.

**Comment by JoshuaLampert** [comment]
The same applies to `Ngon` (apart from `Triangle` and `Quadrangle`), `Polyarea`, `Pyramid`, and `Wedge`.

**Comment by mikeingold** [comment]
Folding this back into #28
