### ISSUE TITLE
Unit test completion could be faster

### ISSUE THREAD

**Issue by mikeingold** [mikeingold/MeshIntegrals.jl#94]
The CI action for running tests currently takes on the order of 20 minutes to complete in GitHub. I suspect that this will be improved via (#67), but additional work could probably be done, e.g.:
- [ ] Minimize the precision of all `@test` integration rules to balance test passing with compute time

**Comment by JoshuaLampert** [comment]
Sounds good. We could also split up the tests into multiple CI GitHub Action runs, where each GitHub Action job runs a different subset of the tests.

**Comment by mikeingold** [comment]
This was helped somewhat by #96, which improved overall performance by strong 10%.

**Comment by mikeingold** [comment]
This was helped again by #100, which reduced CI time by about 2 minutes.
